### ISSUE TITLE
OS X ignores F_NOCACHE if you do a cached read

### ISSUE THREAD

**Issue by cobarx** [ronomon/direct-io#1]
Thanks for creating this library, it's perfect for what we need. I created a script to test doing direct IO on OS X. I'm reading a 240 MB file off an SD card, so the disk cache should be effectively non-existent.

Flag set to 1: 13.6s
Flag set to 1: 13.6s
Flag set to 0: 13.6s
Flag set to 0: 0.3s
Flag set to 1: 0.3s
Flag set to 1: 0.3s

It appears that as long as you do non-cached reads, you get direct IO, however the moment it's loaded in the cache, the `F_NOCACHE` flag gets ignored. 

SD cards tend to be pretty unreliable, so we want to write files to the card and then immediately read them back to ensure the contents were written without any errors. I'm concerned that the file will still be in the filesystem cache even with the `F_NOCACHE` flag set since we just wrote it.

Also, it looks like you completed the work to support direct IO on Windows via libuv. Is that something that is ready to be implemented now? We'd love to turn this on for Windows as well.

```
const directIO = require('@ronomon/direct-io');

const path = '/path/to/file';
const cache = 1;
let fd, info;
info = fs.statSync(path);
const alignedSize = Math.ceil(info.size / 4096) * 4096;
const alignedBuffer = directIO.getAlignedBuffer(alignedSize, 4096);
console.log('Size', info.size, alignedSize);
fd = fs.openSync(path, 'r');
console.log('Set flag to', cache);
directIO.setF_NOCACHE(fd, cache, () => {
  fs.read(fd, alignedBuffer, 0, alignedSize, (err, bytesRead, buffer) => {
    console.log('Read', bytesRead);
    fs.closeSync(fd);
  });
});
```

**Comment by cobarx** [comment]
Found this issue:
https://github.com/axboe/fio/issues/48

It appears that if a file is already in the page cache, setting `F_NOCACHE` has no effect. It might be worth adding some notes in the docs to cover this, as that is different than how `O_DIRECT` behaves. I'm going to try working around this by setting `F_NOCACHE` as well.

**Comment by jorangreef** [comment]
Thanks @cobarx, I am glad it's useful for you!

> It appears that if a file is already in the page cache, setting F_NOCACHE has no effect. It might be worth adding some notes in the docs to cover this, as that is different than how O_DIRECT behaves. 

I was aware of the issue through discussions in libuv but should definitely have documented it here! From previous googling, `O_DIRECT` itself has the potential for issues so I would not consider `O_DIRECT` itself 100% reliable. At least this case with `F_NOCACHE` is far more cut and dry and could easily be avoided if people know about it.

> SD cards tend to be pretty unreliable, so we want to write files to the card and then immediately read them back to ensure the contents were written without any errors. I'm concerned that the file will still be in the filesystem cache even with the F_NOCACHE flag set since we just wrote it.

Good idea. Would you mind testing if `F_NOCACHE` still reads from the cache if the cache is populated through another open file descriptor (i.e. not that of your own process)? If that is the case, do you know of any `ioctl` call or C call to flush the cache for a file descriptor on OS X? Perhaps I could add support for it.

> Also, it looks like you completed the work to support direct IO on Windows via libuv. Is that something that is ready to be implemented now? We'd love to turn this on for Windows as well.

Yes, watch this space.

**Comment by jorangreef** [comment]
Support for `O_DIRECT`, `O_DSYNC`, `O_EXLOCK`, `O_SYNC` has been added on Windows.

The README has been updated in several places, including `F_NOCACHE`.
