### ISSUE TITLE
Loop device,  SG_GET_VERSION_NUM failed (Linux)

### ISSUE THREAD

**Issue by etcher123** [ronomon/direct-io#4]
Trying to use `getBlockDevice()` on a loop device on Linux.

```
var blockdev = dio.getBlockDevice(fd, function(e) {
  console.error('Couldn\'t get block device: ' + JSON.stringify(e.message))
})
```
It gives me `Couldn't get block device: "SG_GET_VERSION_NUM failed"`

Is it expected?

**Comment by jorangreef** [comment]
Yes, I think a loop device is not a true block device so that it wouldn't expose the SCSI commands we need to interrogate serial numbers etc. that's why the command is failing.

**Comment by jorangreef** [comment]
`getBlockDevice()` is meant to be called on a true physical (not pseudo file-backed) block device.

Does that help?

**Comment by etcher123** [comment]
Hi, and sorry for not answering earlier.

> getBlockDevice() is meant to be called on a true physical

Understood, thanks for the precision.
